listen              1935;
max_connections     1000;
daemon              off;
srs_log_tank        console;

http_api {
    enabled         on;
    listen          1985;
}
http_server {
    enabled         on;
    listen          8082;
}
rtc_server {
    enabled on;
    listen 8000; # UDP 端口
    # 保持为你的局域网 IP，确保 WebRTC 握手正确
    # candidate 10.49.249.230;
    # candidate 192.168.31.203;
    candidate 10.5.246.240;
}

# 使用通用配置，无论客户端用 IP 还是域名推流都能触发回调
# vhost 10.49.249.230 {
#vhost 192.168.31.203 {
vhost __defaultVhost__ {
 rtc {
        enabled     on;
        rtmp_to_rtc on;
        
        nack on; 
	twcc on;
    }

    play {
        gop_cache       off; # 极其正确，关闭缓存实现秒开
        queue_length    0.1; # 进一步压缩到 0.1
        mw_latency      100; # 毫秒级合并发送，降低 CPU
    }

    http_hooks {
        enabled         on; 
        # 放弃 host.docker.internal，直接用局域网 IP   10.5.246.240      10.49.249.230   192.168.31.203
        on_publish      http://10.5.246.240:8081/api/v1/srs/on_publish;
        on_unpublish    http://10.5.246.240:8081/api/v1/srs/on_unpublish;
    }
}