listen              1935;
max_connections     1000;
daemon              off;
srs_log_tank        console;

http_api {
    enabled         on;
    listen          1985;
}
http_server {
    enabled         on;
    listen          8080;
}
rtc_server {
    enabled on;
    listen 8000; # UDP 端口
    # 保持为你的局域网 IP，确保 WebRTC 握手正确
    # candidate 10.49.249.230;
    candidate 192.168.31.203;
}

# 使用通用配置，无论客户端用 IP 还是域名推流都能触发回调
# vhost 10.49.249.230 {
vhost 192.168.31.203 {

    rtc {
        enabled     on;
        rtmp_to_rtc on;
    }
    http_hooks {
        enabled         on;
        # 放弃 host.docker.internal，直接用局域网 IP
        # on_publish      http://10.49.249.230:8081/api/v1/srs/on_publish;
        on_publish      http://192.168.31.203:8081/api/v1/srs/on_publish;
        # on_unpublish    http://10.49.249.230:8081/api/v1/srs/on_unpublish;
        on_unpublish    http://192.168.31.203:8081/api/v1/srs/on_unpublish;
    }
}